### ISSUE TITLE
Code Review 1

### ISSUE THREAD

**Issue by JaxkDev** [mwilko/OOP1MWILKO#1]
https://github.com/mwilko/OOP1MWILKO/blob/c188f3a1a351c1ff43158be715483737bc1559d6/CMP1903M_A01_2223/Pack.cs#L18-L19
https://github.com/mwilko/OOP1MWILKO/blob/c188f3a1a351c1ff43158be715483737bc1559d6/CMP1903M_A01_2223/Card.cs#L9-L13
For the card variables, there seems to be a discrepancy between the comments/criteria and the variable types here.

---

https://github.com/mwilko/OOP1MWILKO/blob/c188f3a1a351c1ff43158be715483737bc1559d6/CMP1903M_A01_2223/Card.cs#L11
Did we consider implementing any set method validation?

---

https://github.com/mwilko/OOP1MWILKO/blob/c188f3a1a351c1ff43158be715483737bc1559d6/CMP1903M_A01_2223/Pack.cs#L12
Nice use of static to ensure only one pack exists!

However, should we be having multiple packs for different shuffles? Have you considered having only one pack variable to better match the criteria?
https://github.com/mwilko/OOP1MWILKO/blob/c188f3a1a351c1ff43158be715483737bc1559d6/CMP1903M_A01_2223/Pack.cs#L13

This could also significantly reduce the amount of work needed in dealing cards here!
https://github.com/mwilko/OOP1MWILKO/blob/c188f3a1a351c1ff43158be715483737bc1559d6/CMP1903M_A01_2223/Pack.cs#L95-L123

---

Shuffling algorithms look very nice, well done !

https://github.com/mwilko/OOP1MWILKO/blob/c188f3a1a351c1ff43158be715483737bc1559d6/CMP1903M_A01_2223/Pack.cs#L65
~~Does this get the last half or just the single card at position 26? (I assume the second parameter shouldn't be `halfpack`)~~

---

https://github.com/mwilko/OOP1MWILKO/blob/c188f3a1a351c1ff43158be715483737bc1559d6/CMP1903M_A01_2223/Pack.cs#L81-L85

Good error handling here for unknown shuffle types!

**Comment by JaxkDev** [comment]
Student - Jack Honour - 21203747

**Comment by mwilko** [comment]
Thanks for the review Jack,  

I have changed the suits and values properties and lists to ints from strings. After this i added validation for the set methods of both the value and the suit. I then changed the riffle shuffle algorithm to include be more readable and included only one list across the program to make the program more reliable.

**Comment by JaxkDev** [comment]
Finally,

You've also made some good comments throughout your code such as:

https://github.com/mwilko/OOP1MWILKO/blob/60e15c3f1a926117e86e6f6f29564f245fb90426/CMP1903M_A01_2223/Testing.cs#L28-L29
https://github.com/mwilko/OOP1MWILKO/blob/60e15c3f1a926117e86e6f6f29564f245fb90426/CMP1903M_A01_2223/Card.cs#L18
https://github.com/mwilko/OOP1MWILKO/blob/60e15c3f1a926117e86e6f6f29564f245fb90426/CMP1903M_A01_2223/Pack.cs#L61-L64

Well done :)
